version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: ch
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./ch_config.xml:/etc/clickhouse-server/config.d/postgres.xml
    depends_on:
      - postgres
    restart: unless-stopped

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: "supersecretkey"
      ADMIN_USERNAME: "admin"
      ADMIN_EMAIL: "admin@superset.com"
      ADMIN_PASSWORD: "admin"
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - clickhouse
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debug
      "
    restart: unless-stopped

volumes:
  pg_data:
  ch_data:
  superset_home:
